general {
    hide_cursor = true
    grace = 0
}

animations {
    enabled = true
    bezier = smooth, 0.25, 1, 0.5, 1
    animation = fadeIn, 1, 6, smooth
    animation = fadeOut, 1, 6, smooth
    animation = inputFieldDots, 1, 2, smooth
}

background {
    path = /home/superior/Pictures/lock.jpg
    blur_passes = 3
    blur_size = 6
    brightness = 0.55
    vibrancy = 0.2
}

label {
    text = cmd[update:1000] date +"%I:%M"
    color = rgba(255, 255, 255, 1.0)
    font_size = 120
    font_family = JetBrainsMono Nerd Font ExtraBold
    position = 0, 220
    halign = center
    valign = center
}

label {
    text = cmd[update:60000] date +"%A, %d %B"
    color = rgba(232, 228, 255, 0.9)
    font_size = 22
    font_family = JetBrainsMono Nerd Font
    position = 0, 110
    halign = center
    valign = center
}

label {
    text = Welcome back, S10
    color = rgba(200, 200, 200, 0.8)
    font_size = 16
    font_family = JetBrainsMono Nerd Font
    position = 0, 40
    halign = center
    valign = center
}

input-field {
    size = 320, 55
    outline_thickness = 2
    outer_color = rgba(255, 255, 255, 0.6)
    inner_color = rgba(0, 0, 0, 0.6)
    font_color = rgba(232, 228, 255, 1.0)
    check_color = rgba(154, 168, 255, 1.0)
    fail_color = rgba(255, 85, 102, 1.0)
    placeholder_text = <i>󰌾  Enter password</i>
    fade_on_empty = true
    rounding = 16
    dots_spacing = 0.3
    position = 0, -120
    halign = center
    valign = center
}
