add_newline = true
format = "$directory$git_branch$git_status$cmd_duration$line_break$character"

[directory]
style = "bold white"
truncation_length = 3

[git_branch]
format = "[on $branch]($style) "
style = "dimmed white"

[git_status]
style = "dimmed white"

[cmd_duration]
min_time = 2000
format = "[took $duration]($style)"
style = "dimmed white"

[character]
success_symbol = "[❯](bold white)"
error_symbol = "[❯](bold red)"
